theme: jekyll-theme-minimal
title: Zhen Yuan (袁振)
description: Welcome to my homepage! I am a graduate student major in computer science. 

我记得在大一的时候，我几乎被线性代数课吓退了。那时的风格是：公式1，定理2，引理3等等。一些比如，从何而来，为什么这么做，有什么几何意义这样的信息，都没有涉及。指定的教材是一个很薄的绿皮书，除了公式和证明过程再没有多余的叙述性句子。翻阅图书馆千篇一律的参考教材尤其加重了我的焦虑。在中学到大学我遇到过一些有着聪明脑袋的人，他们的学业绝大部分停止在本科。我不知道是不是填鸭式教学让他们失去了趣味。如果你也有过同样的困惑，或许ocw.mit.edu会帮到你。这是大二一个闷热的下午，我在图书馆机房偶然翻阅到的。
