theme: jekyll-theme-minimal
title: Zhen Yuan (袁振)
description: 欢迎来到我的主页。理查德·费曼（Richard Phillips Feynman，物理学家）在他的自传里写道，最好的学习方式就是将知识教会给别人，所以，我在这里记录了一些学习笔记。这些笔记主要包括机器学习、深度学习、心理学和一些杂文。关于心理学：我每天绝大部分时间都是在和电脑打交道，但其实我更想和人打交道。你如果对心理学存在某些偏见，比如读心术、如何控制别人等等，可能是因为接触了一些大众读物而非科学著作。心理学是让我们更好地认识自己和理解他人的学科。关于杂文：我喜欢阅读，也喜欢写作，只是文笔拙劣。
typora-root-url: https://raw.githubusercontent.com/zhensyuan/imgs/master/yuan.png
