theme: jekyll-theme-minimal
title: Zhen Yuan (袁振)
description: Welcome to my homepage! Writing is really helpful and I'll share my paper readings in this page. These notes contain my personal understanding of machine learning and deep learning, and currently I focus on graph neural networks. If you have some ideas or find something wrong, or you just want to write something to me, please email me zhen.s.yuan AT outlook DOT com
